import React from 'react';
import { LORE_TOPICS } from '../constants';

const HomePage: React.FC = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-4 md:p-8">
      <header className="text-center mb-12">
        <h1 className="text-5xl md:text-6xl font-bold text-bays-cyan tracking-wider">
          Bay Lore IPC
        </h1>
        <p className="text-bays-text-muted mt-4 text-lg">
          Your AI-powered guide to the universe of Baystation12.
        </p>
      </header>
      
      <main className="w-full max-w-4xl">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {LORE_TOPICS.map((topic) => (
            <a
              key={topic.slug}
              href={`#/lore/${topic.slug}`}
              className="bg-bays-dark-200 p-6 rounded-lg shadow-lg hover:bg-bays-dark-300 transition-all duration-300 ease-in-out transform hover:-translate-y-1 focus:outline-none focus:ring-2 focus:ring-bays-cyan"
            >
              <h2 className="text-2xl font-semibold text-bays-text mb-2">{topic.name}</h2>
              <p className="text-bays-text-muted text-sm">{topic.description}</p>
            </a>
          ))}
        </div>
      </main>
      
      <footer className="text-center mt-12 text-bays-text-muted text-sm">
        <p>Select a topic to begin your inquiry.</p>
        <p>All responses are generated by an AI assistant based on curated lore documents.</p>
      </footer>
    </div>
  );
};

export default HomePage;