// lore_data/skrell.ts
export const skrellLore = `The '''Skrell''' are a species of amphibious humanoids hailing from the world of [[Qerr'Balak]], a hot, humid planet with numerous swamps and jungles. More technologically advanced than humanity, their ancient society is now stagnant and threatened by the fast growth of their new allies.

Have a look at the [[Skrell Roleplay Guide]] to get an idea about the Skrell mindset.

===== History =====
As a loose ensemble of City-States, describing the history of the Skrell since they took to the stars is difficult. It is nonetheless worthwhile to note that, despite a lack of central government to keep them in check, the City-States have rarely entered in open conflict between themselves, disputes and tensions being generally settled through negotiation and debate or, in the more extreme cases, covert operations by Skrellian military units.

Rapid population growth has been both a blessing and a curse for the Skrell for millennia, and, despite attempts by Skrellian leaders to curtail it, has not slowed, forcing the Skrell to rapidly expand their territory over the centuries. While the exact number of colonies is unknown, their overall territory is far, far greater in size and scope than what humanity occupies, with Skrellian territory spreading outward into what is ,to humanity, unknown space. That expansion is nowadays a problem for the Skrell, as they repeatedly find themselves boxed-in by the various civilisations that neighbour their ever expanding territory, forcing them to consider changes to how they acquire new holdings and manage their current population.

Despite their technological superiority, Skrellian technological progress has slowed, having somewhat plateaued, with no major breakthrough having been made in the past century. This is mainly due to the Skrellian scientific process, heavily burdened by extensive testing and safety concerns, but also because new technological finds have difficulty spreading across a vast territory lacking centralised organisation and authorities.

There are a number of major events in Skrellian history that are worth noting. The dates have been adapted to the human calendar for more clarity.

* 800 BCE - The Skrellian industrial age begins with the invention of the first assembly line.
* 700 BCE - The first aeroplane is invented.
* 620 BCE - Skrellkind look to the stars as work on the first space shuttle takes off.
* 540 BCE - Skrellkind rejoice as the first successful launch of a space shuttle lands astronaut Q'ikkori Xallic on Qerr'Balak's second moon, Qerr'Malic.
* 200 BCE - The first Skrellian colony is formed on Qerr'Malic.
* 500 CE - Skrell begin exploring outside of their immediate area, establishing colonies and research bases along the way.
* 2038 CE - Skrell travel to Epsilon Ursae Minoris and, while there, flagged the area for further review as a result of strange readings.
* 2132 CE - Skrellian mining fleets discover [[Diona|Dionaea]] Gestalts in previously mentioned Epsilon Ursae Minoris, it is considered a great discovery among all the castes.
* 2233 CE - While on a scouting mission, Skrellian exploration vessels come across a human station badly damaged and entering a meteor belt. The Skrellian vessel moves in to assist, shielding the station from harm by way of their shields. First contact with humanity is made.
* 2239 CE - Trade and Research agreements among Skrell and Humanity are formed, creating a lasting bond.

== Biology ==
<blockquote>''Main Article: [[Skrell Biology]]''</blockquote>Skrell are humanoids with a height averaging from 5'10" to 6'2", females being generally taller than males, though this is a broad average across their massive population with variance going both ways. Their feet and hands are webbed. Their respiratory system is a complex combination of vestigial cutaneous breathing, lungs, and gills placed at the back of the neck and protected by headtails. Their bones are denser and more flexible than human ones, making them less likely to break under shock, Their blood is a dark blue colour. life expectancy ranges from 100 to 120 years, depending on various factors.

The Skrellian life cycle starts as a tadpole, hatching from eggs. During the next six to nine months, said tadpole will grow and develop its adult limbs, along with its gills and headtails during the later stages of development. During this phase,they live underwater and are very vulnerable; even the most minor wound will brutally disturb the tadpole's growth and it is rare that more than five of them survive their infancy.

A Skrell's skin can have a large variety of colours, ranging from dark blue to vivid red, with shades of various shapes across the body. It is slightly translucent in areas, mostly on the headtails, and exudes a thin layer of slime making the Skrell appear somewhat gelatinous at first sight.

Skrellian heads are comparatively simpler than human ones. In place of a nose are slits, lips are almost nonexistent. They have as many facial muscles though most of them are located in the lower area, decreasing the Skrell's ability for facial expressions. Skrellian ears also lack an auricle, its function being taken over by a complex inner canal. Their eyes are larger than a humans,occupying half their face and entirely black when observed from the outside. Their size and position, being further apart than on human faces, give the Skrell a broader field of view. Their vocal cords, accompanied by internal vocal sacs, give them a very large range of pitch, high enough to be partially inaudible to humans.

The headtails vary in size, being longer on females. Their initial purpose was to protect the gills from external contaminants and irritants. Later in their history, Skrell started decorating their headtails with jewellery and various decorations.

The Skrell are vegetarian. Not only are they unable to absorb animal protein, but doing so is likely to cause illness, with food poisoning being possible. Traditional Skrellian foods are heavily based on the fungi-like organisms found on Qerr'Balak.

Despite an extremely low resistance to alcohol, Skrell have otherwise developed a high tolerance to a large amount of chemical substances, a result of their homeworld's flora being generally poisonous as a defence mechanism. Consequently, Skrellian food is generally too harmful for human consumption.

== Society ==

=== Language ===
<blockquote>''Main article: [[Skrell Language]]''</blockquote>The Skrell language — commonly known as Skrellian — can be best described as a series of hums, warbles, and croaks; while it would not make sense to other species, the Skrells intricacies of communication can display a wide variety of emotion and meaning that many human languages cannot.

With other languages, such as Zurich Accord Common, Skrell take on the accent of the person who taught them the language.

Skrell have trouble expressing emotion through simple words and body language when speaking in Zurich Accord Common.

Skrellian written language is, similarly to the spoken language, hard to understand for a non-Skrell. Based on logograms, it contains thousands of different signs, leading to vocal homonyms only differentiated by small variations in the tone and the pitch of the speaker.

Because of the need to facilitate easy naming and communication with other species, and the difficulty of the Skrell language, Skrell adopt different naming conventions for use in non-Skrell space. While a normal Skrell name may well be as long as Uwooziivriziichinovrix Xrivrator'Kloa (far from a typical name) this is considered difficult, lengthy and unwieldy for non-Skrell, resulting in broken up, shortened, rough translations such as Uwoozii Vri'Vrix being adopted for inter-species communication. In some cases, Skrell choose to forgo such a name style and instead take either a nonsense name or one of a specific alien culture for convenience. As such, names like Bartholomew Aramaud and Tria Marsa are also found in use by Skrell in human space.

=== Castes ===
<blockquote>''Main article: [[Skrell Castes]]''</blockquote>One of the main pillars of Skrellian society, the caste system has been in place for millennia on Qerr'Balak. A solution to society's inefficiencies, by immersing the Skrell in various environments shaped to specific needs, goals and values, the castes were able to form generations of specialised Skrell who developed their own values and traditions. As such, castes act as subcultures within the main Skrellian culture, conditioning a Skrell’s life from birth to death and passing it along to their children. The castes are more of a way of life rather than a predetermined path that every Skrell must follow.

* '''Qerr-Katish (High Caste):''' Considered as the leaders of Skrellkind, the Qerr-Katish are the face and soul of Skrellian society. Managers, diplomats, lawyers, they are notably the only caste allowed to fulfil the role of Qerr-Skria, and the only one forbidden from being appointed to the Xaq Moglar. Representatives of the Skrell, Qerr-Katish are highly social beings, sophisticated,and organized. They tend to be rather conservative, although progressive ideas regularly grow within the caste, as a stagnant society is a dying society. They generally are the richest people of a City-State, although their money is generally invested in various endeavours both in and out of Skrellian society. Qerr-Katish families tend to be rather small, being generally limited to one, sometimes two bondings. They often dress in clothing made from softer, shinier materials, long and flowing and has often been compared to the clothing of ancient Chinese nobles by human scholars. Their skin is generally bright green.
* '''Malish-Katish (Caste of the Mind):''' If the Qerr-Katish are the face of Skrellkind, the Malish-Katish are its brain. Scientists of all sorts, they are the ones who allow Skrellian society to grow, be it technologically or ideologically. Highly inquisitive, they are among the more progressive Skrell. However they are not very social, and their emphasis on methodical thinking make them less capable of acting quickly under pressure and handling their feelings in public. They are less wealthy than the Qerr-Katish, their status affords them much comfort. Their families are generally made up of two or three bondings. People within this caste often wear clothing made from the same materials as the Qerr-katish yet more simplified, white shirts and black pants with possible jewelry for decoration. Their skin is generally pale green, sky blue or pale yellow.
* '''Kanin-Katish (Caste of the Builder):''' The main workforce of the Skrell. With activities ranging from goods production to services and engineering, they occupy the largest and most diversified sector of Skrellian activity. They are a very tightly knit community, both within their families and with their co-workers. Very traditional, they hold rather conservative views on the world, and their pack mentality dampens most individualism. Their families are frequently large, three or four bondings. As such, they are often among the less wealthy Skrell, but they do not seem to mind, as their work is the life and blood of Skrellian civilization. They possess a strong mental and physical resilience. Their clothing is made to last, the personality of the Skrell often being shown through arm bands or headtail decorations of any kind. Their skin is generally red, orange, pale yellow, dark orange or black.
* '''Talum-Katish (Caste of the Artist):''' One would be mistaken to think Skrell do not consider arts much. This important sector of Skrellian society is handled by the Talum-Katish: artists, chefs and entertainers. They compete with the Qerr-Katish’s role as representatives of Skrellkind, although in a different way. They are in fact frequently on the public scene. The Talum-Katish are the most individualistic members of Skrellkind, though they enjoy busy social lives. They are the free-thinkers of Skrellian society, often at odds with conservative castes. They tend to reproduce a lot, multiplying their encounters with various partners. Their clothing is often an odd mix of Qerr-Katish and Malish-Katish, as they often wear clothing that are colourful shirts, adorned with embroidery and their headtails sparkling with gold. Their skin is generally purple, blue, pink, orange, red or white.
* '''Raskinta-Katish (Caste of Warriors):''' Rarely seen outside Skrellian society, they are the ones who ensure the safety and stability of Skrellian civilisation, both against internal and external threats. The military caste of the Skrell, most end up working for the various City-States either in the police or as a career soldier, although some of them end up working for private security or as entertainment fighters. They are very conservative, deeply committed to their community, caring very little for self-development and personal satisfaction. Their martial training leaves very little time for indulgences, and they are trained to be expert tacticians and possess organisational skills second only to the Qerr-Katish. They are among the poorer castes of Skrellkind, with large families of three or four bondings. They possess strong social cohesion. These are often the hardest to spot among a crowd because they intentionally wear clothing other castes are known for while not working, however they tend to stick to clothing that is easy to move in and often dark blue. Their skin is generally green, blue, black, brown or yellow.

=== Politics ===
<blockquote>''Main article: [[Skrell Politics and Economics]]''</blockquote>Contrary to what one might assume, the Skrell are not united under a single, homogenous political entity. Due to historical reasons and cultural and political stigma, large nations are virtually unheard of, although examples can be found throughout history.

Instead, the Skrell are divided in individual and independent City-States, ruled by hereditary monarchs from the Qerr-Katish caste, the legislative power being held by an assembly, the Xaq Moglar, composed of teachers from the city's Academy. The monarch themselves (called a Qerr-Skria in simplified Skrellian) is always surrounded by a council with an advisory role, the Qerr-Koal, composed of respected senior members of the city's castes.

=== Economy ===
For the Skrell, money is a temporary thing. Skrellian currencies are printed with a temporary filigree, made from the spores of a very specific luminescent mushroom on Qerr'Balak. The luminescence fades completely after two years, after which a Skrellian bill is no longer usable. Each filigree includes the date of the bill’s printing, allowing the verification of the bill’s authenticity by comparing the date and the expected luminosity of the spores.

This means Skrell cannot hoard money, and are instead incentivised to spend it, be it by buying goods and services, or investing it in various endeavours. If a Skrell wishes to preserve money for future projects, or simply for financial safety, their only recourse is to loan that money, without interest, to the City-State, for a set duration decided at the start of the loan. When the government gives back the money, the bills are freshly printed for a new 2-year long period of use.

That way, the Skrellian City-States are consistently supplied with their citizens’ money, negating entirely the need for taxes in their society. Since money is constantly printed and destroyed, inflation is a very minor phenomenon, and the gap of wealth between the various castes, while still existent, is far less consequential than in humans societies.

While human money is technically unusable in the Skrellian territories, most City-States accept it in exchange for freshly printed Skrellian bills, which the government then uses for exterior trade and to exchange with Skrellian corporations wishing to trade with humans.

== Culture ==
<blockquote>''Main Article: [[Skrell Culture]]''</blockquote>Despite what one would expect from such a pragmatic society, the Skrell place great importance on their arts and entertainment. The existence of the Talum-Katish as a caste of artists is but one indication of it.

=== The Arts ===
For obvious reasons due to their biology, Skrell give a lot of importance to music: It is actually quite rare to meet a Talum-Katish who does not at least possess average singing skills. While Skrellian artists are still looking to produce enjoyable music, they prefer to avoid the restrictions of a codified system, allowing them more freedom in their creations. Voice plays a very large role in their music. Because of the specifics of their written language, Skrell did not develop a printing system until very late in their development, meaning knowledge had to be spread either by handwritten books or orally; in the latter case, songs quickly became the norm to transmit that knowledge. Skrell do have a large array of musical instruments, most electronic, to serve as a support to the vocal lead, but generally, voice stays at the forefront of mainstream Skrellian music.

Speaking of written language, Skrellian literature has, too, seen its share of evolutions over time. In recent years there has been a surge in the popularity and production of poetry books. Many modern writers use the visual impact of their complex, intricate written language to convey their message.

In the domain of visual arts, the Skrell have a long, complex history of painting and sculpting. In their early days, they used to spray dye made from their local, diverse vegetation onto small ponds, using the water as their canvas. Such works were ephemeral at best, and while more stable supports have now been widely adopted, pond-painting is still a mainstay in Skrellian art.

Sculpting itself has seen its share of changes. While ancient painters were busy with their ponds, early Skrellian sculptors saw potential in the massive Kol’mo, mushrooms that can be found on most of Qerr'Balak’s surface. In the modern era Talum-Katish have adopted the use of genetic engineering and, thanks to the very primitive genetic code of the Kol’mo, applied it to artistic expression, growing surrealistic mushrooms while completely bypassing the need for any physical sculpting.

=== Sports ===
All Skrell practice sports to a certain extent, although the specifics generally depend on caste. While the Kanin-Katish and Raskinta-Katish practice sports that do not shy away from physical effort, the more intellectual castes undertake exercises more fitting to their skills. Most Skrellian sports are played in teams, and with the exception of the Raskinta-Katish’s activities, often lack an actual adversary, preferring to place the players in front of issues waiting to be solved.

As expected of them, Talum-Katish merge sports and arts through dance: with a large amount of them taking place in or under water, they also evolved along a lot along modern technologies, antigravity environments partially replacing the former dancing pools. Water-dancing stays nonetheless a mainstay for Talum-Katish, as water offers entirely different parameters to evolve in. Oddly, Skrellian dance often looks very martial, with human sociologists quickly comparing them to the kata of Eastern Asia.

Malish-Katish practice close to no physical sports. They instead focus on very intellectual activities, ranging from visual puzzles to logical riddles. Once again, these games are generally practiced in teams, although the players are often separated and cannot share intel with their teammates. Each player has thus the task to complete their own part while having no knowledge of the bigger picture.

Lastly, Qerr-Katish, just like Malish-Katish, do not practice a lot of physical activities. They are, however, extremely fond of numerous strategy games, where their intelligence and organisation are put to the challenge. With the rise of virtual reality and advanced artificial intelligence, the concept was taken even further, with full simulations being developed, both as a training exercise and entertainment.

=== Family ===
<blockquote>''Main Article: [[Skrell Family and Education]]''</blockquote>The Skrell are non-monogamous, preferring a large panel of sexual partners for the purposes of reproduction. As such, the notion of human-like marriage is alien to them. However, the need for a family structure still exists, leading to the Skrell Bonding. Instead of forming a constant familial structure to which offspring will automatically be attached, Skrell make a punctual Bonding between both parents when a couple produces a shoal to attach the children to this couple, making them, in effect, a family. This allows legal and social recognition of the progeny by both parents while letting them explore other reproductive opportunities.

The parents rarely stay together after the Bonding. One of them is designated as the Qarr-Maqa, the main parent, responsible for the children, while the other becomes the Qrri-Maqa, who has more of a support role, providing financial aid to the Qarr-Maqa along with other forms of assistance.

Relations between two shoals who share one or both parents are quite distant: At best, they will see each other as something akin to cousins, but generally, they will tend to simply ignore each other, only to meet during large family meetings. On a legal point, however, they do not share any kind of link but the same parent(s).

For the Skrell, gender has no significance outside of reproduction.

=== Education ===
Skrellian education is the basis of Skrellian society. Tadpoles are educated by their parents and interactions with the other tadpoles of their Bonding. When a Skrell enters their “adult” shape, they first enter the first level of academic life, called by the Skrell the Mi-Gloa, the Early Enlightenment. At this point, they learn basic logic, elementary sciences such as mathematics and low-level physics, and Skrellian history. All the Castes share the same lessons, except for the Qerr-Katish, who are taught apart from the rest of society and groomed for leadership.

At the age of 8, the Skrell leave the Mi-Gloa and enter the Qlor-Gloa, the Focused Enlightenment, where the different Castes are separated in different paths of teaching. Here again, the lessons are generalist and leave plenty of specialisation to be done later.

When they reach the age of 15, the Skrell choose the path that will determine their future work: They enter the Keri-Gloa, the Ongoing Enlightenment, for it is believed a Skrell never truly stops learning from that point. From there, a Skrell, called a Keri-Glo’i as long as they are in this system, can leave the Keri-Gloa at the age of 18, which means they will be a Qrri-Mog, a low-class worker, taught but not truly enlightened, or at the age of 25, making them a Qerr-Mog, a fully-fledged Skrellian mind, expert in their area of work. Only the “Qerr-Mog” can hope to one day become Qerr-Koal, experts of their castes and counsellors to their King.

=== Military & Life in Space ===
<blockquote>''Main Article: [[Skrell Military]]''</blockquote>The most common military forces seen in the Skrellian territories are the local reserves of each City-State. In charge of the city’s defense, they also fill the role of law enforcement for the government and thus include the police force. However, their small numbers coupled with the political independence of every City-State limits them in all but domestic and local defence affairs.

To compensate for this, the Skrell formed what they call the Skrellian Defence Task Forces. SDTFs are independent entities formed by several City-States who agree to pool an agreed quantity of resources and manpower for their common safety. Once such a group is formed, they gain full independence from their creators, although they are still informally bound to them as they need the City-States to procure them new workers and resources.

Unsurprisingly, SDTFs are not ruled by Qerr-Katish, but by a Raskinta-Katish commander. They have, however, their own equivalent of a Qerr-Koal council, in the form of the high officers in charge of the various subsections of the organisation.

As for the recruitment, City-States provide the SDTFs with volunteers, after which the military organisation evaluates them to decide how many of them will actually join the group. There is rarely a lack of volunteers for this task, though, as being a SDTF member entails a lot of advantages over a regular inhabitant of a city: Higher wages than with an equivalent ‘civilian’ job, priority when it comes to healthcare and education for their close family. Members of a SDTF also enjoy multi-citizenship across the various founding cities of the organisation, a perk rarely enjoyed in civilian life and a serious motivator for potential recruits.

Contrary to what one might expect, the Raskinta-Katish only represent half to three quarters of a SDTF’s manpower. Kanin-Katish generally hold a strong presence in the task forces, but a smaller amount of Malish-Katish can be found working along their more physical brethren. A few Qerr-Katish work as diplomats and managers for the groups, while Talum-Katish are a very exceptional caste to be seen working in them, only for rare, punctual tasks related to the SDTF’s public image.

The castes themselves take a more complicated shape within the Skrellian military; while the main structure remains, they are subsequently divided into various sub-components, themselves separated into smaller partitions. See further reading for a listing.

=== Crime ===
As a millennia-old civilisation spanning across thousands of star systems, it would be foolish to think the Skrellian territories manage to stay free of criminals and illicit organisations. All across the territories, smuggling rings, extortion rackets, underground science labs engaged in gruesome experiments and organised crime can be found, operating behind the scenes.

However, no group embodies the spirit of Skrellian criminality as the Qerr-Glia do. Ancient Qerr-Katish families, stripped of their status and power in the wake of the Qrri-Qerria war, turned to whatever activity, legal or illegal, could finance their fight to reclaim their former position, thus leading to the formation of the Qerr-Glia.

Forming intricate criminal networks across Qerr'Balak, they expanded along with the rest of Skrellkind, broadening their criminal horizons to the stars. Their activities range from money laundering to the slave trade, including equally reprehensible activities such as the drug trade and blackmail.

While the Qerr-Glia have at their disposal a very large network of relations and maintain several fragile alliances between various families, their only loyalty resides in their own family. They will temporarily hire anyone competent enough to fulfil their goals, wilfully or forcefully, but only the members of the Qerr-Skria family are permanent members of a Qerr-Glia cell. Leaving a Qerr-Glia family is considered high treason by its members, and any leavers would find themselves fiercely hunted down by their former brothers and sisters.

The Qerr-Glia, however, never forgot their Qerr-Katish heritage and as such, embody the same values and ideals, although in a twisted way; skilled liars and manipulators, they rarely engage in the physical aspects of their crimes, preferring to plan subtle schemes executed with cold efficiency. Some families are even said to manipulate the politics of entire sectors to their benefit, placing them in positions of power far higher than the ones they once fought for.

While the Skrellian authorities still struggle to contain them, the Qerr-Glia struggle to find new ways of making profit in the Skrellian territories. As such, the discovery of humans gave them a whole new area to exploit which they took to immediately. It is not unheard of for Qerr-Glia members temporarily joining other criminal organisations as a gesture of goodwill from the family, while already planning on the repayment of the debt tenfold.

=== Religion ===
As a civilisation with a long history and a large and diverse population, it would be surprising if the Skrell did not develop, at some point, some form of religious thought. Science being such a tenent of Skrellian society, however, Skrellian religions are generally focused on the metaphysical study of the universe rather than the mythological aspect of religion. As a result, most religious Skrell hold a monist view of the universe, with their beliefs often being akin to one form or another of pantheism.

== Relations with Other Species ==
The Skrell generally have an ambiguous position when it comes to other species. Centuries of cultural homogeneity and political hegemony has made them very self-confident yet they are very tolerant of other cultures and civilisations in part because of their curiosity for what they don't know or understand. However, they still hold very paternalistic, ethnocentric views of the universe, very interested in influencing other societies, but leery about outside interference within their own.

Of all the known species, the [[Diona|Dionaea]] are the closest allies, even friends of the Skrell. A civilisation they see as non-threatening, Dionaea are often welcomed in Skrellian territories, with many agreements and treaties signed between City-States and gestalts. In particular, the Dionaea unique biology has garnered a large interest from the Skrellian scientific community, with many companies and organisations trying to understand and replicate their allies' strange properties.

By far one of the Skrell's oldest relationships is with the Ascent. Almost a thousand years ago first contact between the Skrell and the Ascent resulted in all out war which harmed both species and their territories massively. This resulted in a stalemate and, finally, peace. Peace, however, has not resulted in overly amicable relations between the two, and the Skrell and Ascent have been locked in a cold war ever since. Though the Skrell are now among the few that the Ascent has a begrudging tolerance for as a result. Today, relations are somewhat cordial, if reserved, in day-to-day exchanges and small scale trade, though espionage and intelligence gathering are widely conducted by both sides, along with the occasional skirmish. Since the arrival of the MSQ's relations have increased, somewhat, in that now Qerr-Katish engage in far many more diplomatic engagements with the Ascent than they did previously.

Humans are still to this day a contentious topic for the Skrell. While allies in practice, many Skrell see that partnership as potentially dangerous, as human culture is in many ways anathema to Skrell culture. Many alarmist thinkers believe that this outside influence might, in the long run, harm the cohesion of their society, causing great upheaval and change to Skrellian society. Nonetheless, most Skrell agree that cooperation with the humans is better than rivalry or worse, open conflict, so both species enjoy a cordial yet cautious relationship.

Skrell relations with [[Positronics|IPCs]] are quite distant. Having never developed sapient AI because of the potential ramifications of doing so, the Skrell prefer to observe the IPCs with caution, yet are still curious to see how a purely synthetic species created by humanity will evolve. While still outlawing their creation domestically, many City-States have recognised that IPC's have sapience, at least in those in which free will is not suppressed (Gen II's.) Skrell tend not to recognise the sapience of Gen III IPC's given their inherent free thought block.

[[Unathi]] are seen as primitive by the Skrell, and their relative distance from the Skrell border have made them mostly unworthy of acknowledgement or contact from the vast majority of Skrell City-States. The few times contact has generally been established by the species are attempts from the Skrell to enlighten the lesser species, with barely any success or appreciation from either side.

[[Vox]] are seen with mistrust in Skrellian society. Most SDTFs have orders to not let Vox ships wander in Skrellian territory and, despite interest in their mysterious past, most Skrell would prefer to avoid having to acknowledge their existence as much as possible.

As a relatively small-scale experiment by human corporations, [[Giant Armoured Serpentid|Giant Armoured Serpentids]] are known, but otherwise ignored by most Skrellian powers. Awareness of GAS has, however, recently increased, with a few City-States becoming aware of the generally enslaved conditions in which humanity keeps GAS. This has led to some controversy, with a few City-States cutting relations with humanity entirely and others still opting for a more covert approach, with rumours of a free GAS reservation being established by a Qerr'Balak City-State, a number of Skrell organisations have begun attempts to free individual GAS to relocate them to the relative freedom of the reserve.

With news of the [[Adherent]] coming from Skrell working in human space a great deal of wary interest has been developing amongst many Skrell City-States scientific elite, with a number of them planning diplomatic and science expeditions to the Adherent home system. Much like IPC's, the Skrell are wary of an entirely synthetic species, though most have their fears assuaged by the relatively benign and helpful manner of Adherents that have been encountered so far. The Skrell look with interest as to how this nation of machines will fare with the wider galactic community.

=== Skrell on the Torch ===
Skrell on board the [[SEV Torch]] can come from all walks of life, with varying levels of professional experience, employment and a myriad of loyalties, though they tend to fall into three distinct camps: military, corporate or independent.

On the uniformed services side, this represents all of the Skrell who are in the [[Expeditionary Corps]]. Following the negotiation of a number of deals with a number of Skrell SDTFs' and their sponsoring City-States, the SCG has created an exchange program allowing Skrell from one of them to volunteer for service in the Expeditionary Corps, while an equivalent EC member has the opportunity to experience service in an SDTF. Skrell serving in the Expeditionary Corps are thus engaging in a period of temporary service in the EC in a roughly equivalent position to one they hold in their SDTF or as is appropriate for their skillset. SDTF members on exchange are, nominally, volunteers. However, a number have been ordered to participate for other, less altruistic reasons. A great many SDTF members experience culture shock as a result of the stark difference in ideology, standards and operating methods between a Skrellian and a human organisation. A somewhat notable exception to SDTF membership is made for Skrell who are volunteering for the position of Explorer (not the rank), with these either being from an SDTFs' R&D section or as representatives and members of a City-States academic body, and are often students conducting a sort of "gap year" to gain experience of human culture and scientific practices.

Many Skrell are employed by a variety of human corporations, particularly those who operate across all of human space, either as loans from Skrellian corporations engaging in their own form of manpower exchange or research agreements, or a few more radical Skrell from the border colonies who have left their home cities in order to use use their highly in demand skills to seek their fortune and gain status within a human corporation.

Lastly are the very few, rarely encountered independent and miscellaneous Skrell. Ranging from the rare independent contractor to a number of observers and investors sent by City-States who have a vested interest in the mission to keep tabs on both mission progress and any scientific breakthroughs or important discoveries. This list is not exhaustive, with a number of Skrell finding their way aboard through other means and for other purposes.

As an amphibian humanoid species from [[Qerr'Balak]], [[Skrell]] have a number of physical distinctions from other species.

== Anatomy ==
Skrell are humanoids with a height averaging from 5'10" to 6'2", females being generally taller than males, though this is a broad average across their massive population with variance going both ways. Amphibians coming from the warm, humid swamps of Qerr'Balak, their ectothermic bodies still carry several characteristic of water-dwelling species: their feet and hands are webbed, to various extents from one person to another and their respiratory system is a complex combination of vestigial cutaneous breathing, lungs, and gills placed at the back of the neck and protected by a set of three limp appendages commonly called headtails. Their bones are denser and more flexible than human ones, making them less likely to break under shock. Their blood contains hemocyanin instead of hemoglobin, giving it a dark blue colour when exposed to oxygen. A Skrell's life expectancy ranges from 100 to 120 years, depending on various factors.

The Skrellian life cycle starts as a tadpole, hatching from eggs a male Skrell fertilises with internal reproductive organs. During the next six to nine months, said tadpole will grow and develop its adult limbs, along with gills and headtails during the later stages of development. During this phase, the Skrell is forced to live underwater, and is very vulnerable: illness, environmental changes, and even the most minor wound will brutally disturb the tadpoles growth. Out of the fifty spawn generally birthed at the same time, it is rare that more than five of them survive to infancy. The transition to their next stage of growth is progressive. The Skrell is around 30 centimetres long at this point and doubles in size over the next month. Underwater, the gills start functioning to compensate for a now insufficient cutaneous respiration system, and their now-developed lungs allow them to take its first steps on land. Once past the tadpole stage, the Skrell's growth is far slower, reaching proper adulthood after twenty years, with no further radical change to their physiology.

A Skrell's skin can have a large variety of colours, ranging from dark blues and vivid reds to bright greens and jet black, with shades of various shapes across the body. It is slightly translucent in areas, mostly on the headtails, and exudes a thin layer of slime making the Skrell appear somewhat gelatinous at first sight. This slime has the added benefit of protecting the sensitive skin of a Skrell, preventing minor injury and irritation from chemical and gaseous substances out of the water. Despite being insufficient to fully supply the Skrell in oxygen, their skin still retains its respiration capabilities: should one of the lungs fail, the Skrell can normally function, albeit with some difficulty. While they are used to heavy pressures like on their homeworld, the fragile organ that is their skin makes them extremely vulnerable to lower ones; in tolerable amounts, it will only lead to large hematomas while lower pressures will inevitably lead to external and internal hemorrhages and air embolism, causing far more damage faster than a human would suffer. It also allows chemicals to travel easily through the skin, making Skrell somewhat vulnerable to cutaneous contact with chemicals; many drugs developed in Skrellian culture are used that way. A Skrell's sense of touch is overall more sensitive than a human's, but also more crude, lacking in detail.

Skrellian heads are comparatively simpler than human ones. In place of a nose are simple slits, lips are almost nonexistent and while it has as many facial muscles most of them are located in the lower area significantly decreasing the Skrells' ability for facial expressions. Skrellian ears also lack an auricle, its function being taken over by a complex inner canal. Their eyes are far larger than human's, generally occupying half their face and entirely black when observed from the outside. Their size and their position, being further apart than on human faces, gives the Skrell a broader field of view. They also allow the Skrell to see better underwater and in the dark, although they are very sensitive to bright lights and fast changes in luminosity. Skrell see colours more vividly, with blue being a predominant one and ultraviolets being partially visible. In addition to the eyelids, the eyes are also protected by a nictitating membrane, most often seen when the Skrell is underwater. Skrellian hearing is, in most regards, far superior to humans. Their hearing range is close to a dog's, and while they have more difficulties to identify the location of a sound, they do not suffer from a decrease in ability under water. While their sense of taste is very delicate, allowing them to detect potential dangerous substances in their food, their sense of smell is underdeveloped, both lacking in sensitivity and scent distinction. Their vocal cords, accompanied by internal vocal sacs, give them a very large range of pitch, the upper levels being inaudible to humans.

The aforementioned headtails vary in size, being longer on females. A thinner skin allows the veins to be seen, much like hands. Their biological purpose is to protect the gills from external aggression, such as dust and microbes when outside of water. The sterile, dark and humid area quickly led female Skrell to store their fertilised eggs between the neck and the headtails, the slime preventing them from falling off except in case of violent movements. Later in their history, Skrell started decorating their headtails with jewellery and various decorations, despite this practice sometimes leading to infections near the gills.

The Skrells' physical appearance leads to the more xenophobic elements in human societies calling them frogs, salamanders, squidheads, and other less pleasing names, although the Skrell pay little attention to these remarks born of ignorance and false assumptions.

== Diet ==
The Skrell are vegetarian, as indicated by their large, molar-like teeth. Not only are they unable to absorb animal protein, but doing so is likely to get them sick and nauseous, with food poisoning being possible if meat is ingested in too large quantities. Skrellian traditional foods are heavily based on the fungi-like organisms found on Qerr'Balak, with prepared food being the average meal for the common populace.

Despite an extremely low resistance to alcohol, Skrell have otherwise developed a high tolerance to a large amount of chemical substances, a result of their homeworld's flora being generally poisonous as a defence mechanism. Consequently, Skrellian food, and many of their medicines and herbal remedies, are generally too harmful for human consumption.
`;
