// lore_data/unathi.ts
export const unathiLore = `The '''Unathi''' (U-nah-thee) are tall reptilian humanoids from the planet [[Moghes]]. Their scales are hard and plate-like, except for the softer ones that line the inside of their legs, armpits and groin. Unathi society is based on blood relations, and is split across regional, religious and, since recently, political lines. While the outsiders think of them as primitive brutes, the Unathi themselves take pride in honouring millennia-old traditions and upholding their faith, with the core ideas being Organic Growth and Continuity.

== Biology ==
The Unathi are a mesothermic species, with body temperature marginally higher than the ambient. They suffer from fatigue and may enter torpor when exposed to extremely low temperatures. Their hearts have two valves that are spread across their chest, which makes it sound like they have two hearts instead of one. Their ribs are set like armour plates that interlock under their chest, protecting their vital organs expertly. They have a very long, forked tongue, similar to that of a serpent, allowing them to sample the air around. It can stretch up to half a meter in length.

The average male Unathi stands around seven and a half feet tall. Savanna Sinta are said to be the tallest among all Unathi. The [[Yeosa'Unathi]] and Salt Swamps clans tend to be somewhat shorter, while those of the Diamond Peaks tend to be of average height (albeit heavily built). Female Unathi of all backgrounds are usually about half of a foot shorter, and tend to have rounder features compared to their male counterparts. Both stand on digitigrade legs with clawed feet that make wearing standard shoes painful.

The Unathi are a carnivorous species. Their diet consists mostly of meat, although they are able to consume plants and fruits. They barely get any nutrition from plants, which are mostly used as garnish or decoration. It is important to notice that some types of carbohydrates, especially monosaccharides may have an adverse effect on Unathi health and brain functions. Table sugar and fructose cause confusion and hallucinations in Unathi adults, and in high doses can cause lasting brain damage. Because they lack a second palate, Unathi cannot breathe while they are eating.

Unathi require a regular food intake, owing to their well-developed brain and proactive lifestyle. Normally their needs are fairly modest, and they can go on for a while without food or drink - however, in a cooled environment of spacefaring vessels and stations the nutrients are consumed at an increased rate, especially if the Unathi in question is cryogenically frozen. If a Unathi spaceman does not receive proper nourishment throughout the day, their internal organs begin to work themselves over and deconstruct.

Moreover, Unathi possess the ability to regenerate their limbs and restore some damage that happens to their body, a trait that developed from an incredibly powerful digestive system and other related internal organs, focused on breaking down animal protein. This, however, drains their body of resources quickly, resulting in starvation. With the right conditions, a Unathi could theoretically live for 700 years if not more, but Moghes is not habitable enough to allow this longevity.

While a healthy specimen would normally be able to regrow lost limbs and damaged internal organs, given time, those Unathi living in industrialized or contaminated areas, especially around larger city-states on either Poles, may suffer a considerable decrease in their ability to regenerate appendages. To alleviate that, some polar denizens have resorted to using handicraft or imported prosthetics in place of lost limbs. However, while those can be constructed or maintained with relative ease, polar Unathi lack the ability to produce more complex synthetic organs; moreover, stronger internal regeneration makes it difficult and counterproductive to install those inside the body, considering violent rejection reactions that may arise. It is important to remember that a robotic limb is seen by most rural (and Polar) Unathi as a sign of sickness, and few would boast having one.

The reproductive system of a Unathi is very similar to that of Earth reptiles. Females lay eggs, with the average clutch being somewhere between one and three. They have a six month gestation period, after which they are laid in a humid, warm area. After two to three weeks, the fetus is fully developed and hatches from the egg, ready to start the cycle anew.

=== Unathi Life Cycle ===
<blockquote>''Main article: [[Unathi Life Cycle]]''</blockquote>

=== Behavior ===
Irritation or heightened emotion is expressed by thumping the tail against the ground. Verbal exclamations are also common. Such exclamations would be short barks, a rattling of the throat, or 'chuffing' (forceful exhalations of air from low in the throat). Unathi who are anxious or worried might sway (similar to snakes), hiss, or sample air more often than necessary. Being mesothermic, Unathi are unable to regulate their own body temperature very well and are more prone to hyperthermia. Overheated Unathi becomes sluggish and drowsy.

Intimate gestures between Unathi include twining necks, twining tails, and touching foreheads/muzzles. Hugging is usually considered something done by children, avoided by adults. It is unacceptable to touch Unathi tail, or to touch them at all before introductions are undertaken.

Baring the throat is the most meaningful expression of trust in another Unathi. It’s often used as a showing of extreme trust, compassion or admittance of shame. Within honorable contexts, clawing or biting the exposed throat is perfectly allowed.

=== Language ===
'''Sinta’Unathi''' is the main grouping of Unathi languages. Though there is a variety of them due to existing geographical divisions, they are all incredibly similar (save for pronunciation of some things), leading them to be grouped together into one language by other species. The main sounds of it are like that of an animal to the Human ear, with harsh syllables and extended phrases that seem to have either no breaks in syllable count or far too many. The written language of the Unathi is based around a circular structure, with words and phrases represented by curves, long bent lines, sharp marks and, of course, circles. All of it seems like what someone with claws would write into the dirt.

=== Naming ===
The first name of a continental Unathi is their personal or family name, while their last name is invariably the title of their clan. This means, for example, that Dhrekss Gnarssis is a member of the Gnarssis Clan. Males often have unique first names chosen by parents or themselves, although it's not uncommon to have a father and his senior son bearing the same first name, which is considered the official title of the family. Daughters too usually keep the name of their family, adjusted to feminine form. Upon marriage, the newlyweds adopt the last name of the clan they are staying with.

Unathi names are heavy with harsh sounding consonants and short susurrated vowels. An example would be Dhreks Gnarssis or Bhink Khambasshk.<blockquote>''Gios Insthys is a member of the Insthys Clan, and a son of Gios Insthys. Once Gios became a full-grown, he adopted the name Gharr Insthys.''</blockquote>It is a social faux-pas for non-family members to use a Unathi's first name. First names may be used in moments of privacy, when speaking to a very intimate other, or by parents to refer to their children. However, utilizing the ''full name'' is acceptable to distinguish between members of the same clan in formal situations.

== Society ==
Unathi society is based on blood relations, and is split across religious, ethnic and even climatic lines. The three basic elements of Unathi identity are, in order of importance, their '''Clan''', their '''Faith''' and the '''Region''' they hail from, although the last two may vary. While Unathi are well-aware of belonging to a certain species, those three things ultimately fuel the division between them as a whole.

=== Clans ===
<blockquote>''Main Article: [[Unathi Clans]]''</blockquote>'''Clan''' is, essentially, a close-knit group of Unathi families of common ancestry. Apart from kindred blood and shared history, they are often bonded together by common property – even though each family may hold its own possessions, those ultimately contribute to the well-being of the entire clan. The clan system plays a major role in the survival of individual Unathi even in the most hazardous corners of Moghes.

Clans are led by a '''Kaahnepo''' and a '''Matriarch'''. The Kaahnepo is a senior clan-member that leads the clan for life, and new ones are chosen by the council of clan elders (although in smaller clans all free landowners, or even all adult clan-members, may be given voice). Once confirmed by the Matriarch and then led through a series of trials, they lead the clan with the advice of the council, governing aspects of clan life from law and resource usage to external diplomacy. While they take others' opinions into account, Kaahnepos rule as they deem fit – their word is law, and can only be overruled by collective council vote.

The Matriarch (sometimes Patriarch or Parriarch, though the Matriarch title is often used regardless of gender) is chosen exclusively from the eldest and most experienced members of the clan. While the Kaahnepo is tasked with executive decisions, the Matriarch handles logistical and financial matters, in addition to leading the council of clan elders. Most long-term decisions – including land ownership and commercial dealings – are the responsibility of the Matriarch, as is record-keeping; the Matriarch acts as the guardian of the clan's collective knowledge, and ensures that the Kaahnepo's decisions are informed and stay within the clan's best interests.

Members of the Clan all have duties that must be attended to, and the higher standing in the clan often depends on how useful their labour is to the clan. Any self-respecting Unathi will find it honourable to uphold the traditions of his or her clan, and to do and learn as much as possible to make it stronger. However, clan values, laws and traditions may vary considerably in different regions.

As with other spheres of Unathi conduct, some aspects of interpersonal relations are also affected by the clan system. While romance has its place in Unathi society, marriage and family life are considered serious business and an integral part of the well-being of each clan. Since young Unathi are often hard-pushed to formalize the relations with their partner, both families will often go to great lengths to get as much benefit as possible from the arrangement. Boasting or offering tributes to their relatives, or even the heads of their clan may make the process go more smoothly, especially if there is interest in strengthening relations between two clans. Those less lucky will have to repay their in-laws with long years of work – and this is often the only option for exiles or last survivors. Ignoring this ritual is not only likely to spoil relations between families, but may also cast shadow on the troublemaker's clan reputation.

While some clans claim to be millennia-old, it is not a rare occurrence when a new clan is formed. Most often this happens when the old clan grows in numbers, and it's domain becomes overpopulated – some families may split off, migrating in search of new lands to settle, mixing with locals in the process.

One of the important aspects of clan system is inter-clan relations. Legally, those may be based on local customs, religious dogmas or existing convents – however, most often those are driven by an intricate system of personal ties, marriages, oaths and vassal obligations, guaranteed by the blessing of spirits and by brute force. Since there is no uniform legal code, any clan (and, by extension, the Kaahnepo of said clan) holds ultimate authority over their domains. A criminal who escapes the offended party and their vassals and friends may run free – if they are caught however, they are at their captor's mercy. Apart from Kaahnepo's rulings, legal or other disputes may be settled through the elders consulting each other, or through a '''bane''' – a form of traditional duel combat.

Clans will either live in settlements of their own or alongside other clans. Such settlements may grow to become '''city-states'''. While clans may coexist, they often retain their own laws and traditions. In case of large sprawling cities like Mumbak this results in a complicated network of agreements dividing the settlement into spheres of influence, controlled by the ruling families.

All political life on Moghes is based on goodwill and cooperation between clans, since no state actor exists to subdue and bend the clans to their will. The closest thing Moghes has to states are tactical alliances between larger clans, pursuing some common goal. Still, even major organizations like the Hegemony or Ssen-Uuma Convent lack proper authority, and are unable to effectively enforce their will on the rest of the planet's population.

In recent times, city-states have given rise to '''Krukzuz''', a type of clan that other clans have pledged their allegiance to, owing to the former's influence and power . While the vassals enjoy certain benefits as junior partners in the alliance, they have much less say compared to the Krukzuz. Oftentimes the benefits are mutual, with the smaller clan offering experience in crafts or other skills in return for protection under the wing of Krukzuz. Sometimes it's not the case however, with a Krukzuz taking in underling clans that cannot provide much. Those clans may be invested into by the Krukzuz, supported by resources to encourage the clansmen while they attain required skills. Such clans often develop almost fanatical loyalty to the patron Krukzuz as a result of their charity.

To some Unathi, the relations between Krukzuz and underling clans are an embodiment of goodwill between clans; some Krukzuzi have been able to gain much power not in the least because of the positive general opinion among their neighbours. Other Unathi are wary however, seeing the rising power of Krukzuz clans as a breeding ground for future abuse.

Unathi society has slowly changed since approximately the 2110s, a symbol of a clan's power used to be their size and strength but is now slowly shifting towards clans with the highest levels of technology. Most Krukzuz jumped on this opportunity with major ones such as clan Ba'ask leading in development of new technologies. In many of the more industrialized sectors, a clan's size is no longer a show of status but rather the cutting edge of their tech, prompting many Krukzuz to push for greater and greater technological advancements. Clans such as Issarik once considered a insignificant clan are now a major player thanks to their skilled and talented members that push not only themselves, but their Krukzuz up in status befitting their nature.

=== Regions ===
<blockquote>''Main Article: [[Regions of Moghes]]''</blockquote>Moghes is usually divided into six principal geographical zones; going from the poles to the equator, those are the '''Tropical Poles''', '''Savanna Belts''', the '''Great Desert''', '''Salt Swamps''' edging the oceans, and the '''Diamond Peaks'''. All of them produce different kinds of Unathi, with their own unique dialects, traditions, and cultures.

=== Yeosa'Unathi ===
<blockquote>''Main Article: [[Yeosa'Unathi]]''</blockquote>Although Moghes has only one super-continent, a dry one at that, there are a number of island chains and archipelagos in the '''World Sea'''. Those are inhabited by a mysterious, little studied race called '''Yeosa'Unathi''', which differs from continental '''Sinta'Unathi''' in language, culture and even appearance.

=== Faith ===
<blockquote>''Main Article: [[Unathi Cults]]''</blockquote>
[[File:Unathi cults.png|thumb|Unathi Cult Compass. Clockwise from top right: the Grand Stratagem, the Fruitful Lights, Hand of the Vine, Markesheli. Center: Precursor Worship.]]
Throughout the history of the species, faith has been a cornerstone of Unathi society, and a powerful force in any individual’s life. Like on Earth, religious beliefs on Moghes are quite diverse, and are often syncretic or even secular in practice. Surprisingly though, most if not all Unathi share common mythology – a meta-religion – in which the existing beliefs are grounded.

According to Unathi worldview, the world is divided into two planes of reality, which roughly equate to human concepts of “Life” and “Afterlife”. The latter is home to potent entities – the spirits of those who once inhabited the realm of the living. Each spirit holds immense power over the world’s affairs; In order to ensure the normal functioning of natural and societal life, Unathi seek patronage with them, especially with those of their own kin, whom they call the '''Ancestors''' – the ranks of whom every Unathi is bound to join at some point.

The worship of Ancestors is easily the most widespread, and even secular-minded polar dwellers revere their forefathers and other great figures of the past, ancient and recent. However, the mark left by the staggeringly developed '''Precursor''' civilization has given this traditional Unathi religion a peculiar twist.

An important aspect of traditional Unathi religion is the existence of cults, which provide distinct views on what the Unathi should do to fulfill the will of the ancestors better. The main four are '''Hand of the Vine''', '''The Grand Stratagem''', '''Fruitful Lights''' and '''Markesheli'''. While some are more or less associated with particular regions, others are more universal, appealing to a larger portion of the planet's population.

=== Guilds ===
Unathi '''guilds''' are a rough equivalent to the corporations and companies of Humanity and the Skrell. Though by no means as profitable or intergalactic as Megacorporations of Sol, the guilds play an important role in the politics of Moghes by providing various goods and services to clans and city-states. Large and small guilds are proactive in all sectors of industry, although few crafts are truly monopolized.

Apart from having essential skills, a Unathi seeking to join up must know a member of the guild and have work to provide for review. Although the newcomers may be compelled to move closer to the guild's location (with more centralized guilds providing quarters for their members), the connection with one's clan stands – guilds are not neutral organizations, and are often biased towards clans involved.

The hierarchy of the guilds is rather simple, based primarily on age and individual merit. Apprentices answer to the Mentors, which are handpicked among full members by Guild Masters; Those, in turn, report to the Overseers, which are in charge of the workshops. No matter how large the Guild is, a '''Jhoge''' (guild equivalent of clan Kaahnepo) is always at the head, nominated by votes of the senior members of the guild.

Regarding guild names, those tend to be rather lengthy and fanciful, acknowledging guild history, achievements and patrons; titles like «Ancient and Distinguished Order of Boatmakers» and «Most Worshipful Company of Distillers and Oleochemists» are considered laconic.

=== Clothing ===
Due to specifics of Unathi anatomy and Moghes climate, clothing does not matter as much to the locals as it does to humans – in fact, it has been the norm for many settled clans to ditch the garments altogether while at home, only covering themselves during travels. As such, Unathi dress tends to be sturdy and simplistic, made of primitive materials, designed not to come apart when exposed to elements – such as sandstorms, fields of spiny plants and the difficult topography of swamps and rocky wastelands.

Typical materials include coarse cloth (made of '''bho'esshie''', a species of local jute-like plants) and ssisalik leather, produced in large quantities by farmers and nomads alike. Those materials are often fashioned into single-piece garments, allowing to preserve as much material strength as possible, minimizing the amount of seams and joints. Traditional Unathi-made long robe resembles a Roman toga – or an oversized gunny sack, depending on who you ask. Leather garments include cloaks, loincloths, aprons, body wraps and helmets, often worn by the hunters. Among exotic materials, sea silk stands out, frequently used by Yeosa'Unathi to construct deep sea diving suits.

As with bodywear, shoes are typically worn during long travels and marches. Caligae-like thick-soled sandals remain popular with troopers and voyagers, allowing them to traverse great distances on foot.

Sometimes clothes are worn for social reasons. In that case, garments are often decorated, dyed with paints made of crushed oxides, clay and plant matter. Diamond Peaks are known as a major centre for mineral dyes production. Ruddy yellow ochre-based colours, collectively known as '''Blood Paint''', have long been associated with highlanders, who covered their metal armor with painted cloth to prevent light reflection and overheating. Over the years, the popularity of such hues migrated all the way to the poles: peculiarly, the Moghes Hegemony favours Blood Paint for its banners and formal dress, despite the earlier associations. In reverse, when steel cuirass went out of fashion, Ssenuuma Convent adopted bleached grey-brown uniforms, suitable for desert operations.

Other than colour, Unathi may demonstrate their higher standing with jewelry and adornment, although the latter is most popular with Fruitful Lights fanatics, who tend to decorate their clothes with strung beads (made of various materials) and bonecrafts to enhance their abilities.

In modern times, as the city states turned into major industrial centres producing goods for Moghedi and offworld markets, Solar clothing became more prevalent, not only in practical sense, but as a cultural phenomenon as well. Human-inspired overalls, branded sportswear, printed shirts have been ubiquitous on Moghes for the last 30 years – more traditional outfits are now considered formal, worn by elders or the rich as a status symbol. Younger urban Unathi typically wear whatever is most comfortable to them, or whatever they can afford, although certain clans (such as the Kharza) employ a more standard uniform.

=== Calendar ===
Unathi in general tend not to record global history like humans or Skrell have done. Each clan records their own history with the art of “skein-weaving”, practiced by matriarchs and elder females. Carefully preserved patterns of knots woven from thread form an intricate web of Sinta glyphs detailing the events of each Moghedi year, roughly equalling '''400 solar days'''.

Most Unathi keep a basic calendar system to track days and years. Their seasons are '''Moto''' and '''Jua''', which are the equivalent of summer and winter. Temperature changes are mostly felt nearer to the poles, but in the desert the length of days are affected, minorly so depending on the season. The two seasons last roughly two hundred days, so when the two hundredth day of Jua passes, it would be considered a new year.

For example, to predict or recall a certain date, an Unathi would phrase it in a way such as "The twelfth day of Jua, five years ago".

Unsurprisingly, the Unathi keep time tracked loosely by sundials. These primitive yet effective clocks are split up into four quarters. Rather than use numeral digits like humans, they instead pay attention to the slant of the shadow. When it is facing a bearing of zero degrees, then it is considered dawn, a new day. At ninety, breakfast should be over with and Unathi should be starting to prepare for their work day. One hundred and eighty degrees is midday, most commonly seen as a trading rush-hour or a time for large, friendly lunches. When the slant is at two hundred and seven degrees, the work day begins to wind down and the Unathi return home to their clans for their evening meals.

=== Guwandi ===
It is generally agreed that social, economic and private life of each individual Unathi revolves around their clan or the host clan (should they marry into one or be adopted). Sometimes, however, a Unathi may find themselves living outside of the clan system.

Reasons may vary. Some may be driven to such a decision by altruistic considerations: mortally ill or disgraced Unathi can leave their clan to ease their burden and escape the stigma. Others take penance for their unrightful actions against their own kin and those they had obligations towards. The rest are exiled or chased away. In any case, all their possessions are sold off or redistributed, so that the exile may set off for a new life in the wilderness.

Such outcasts are grouped under the collective name of ''''Guwandi'''<nowiki/>', or Ghu'wadhi. As per tradition, Guwandi wander the planet, shunning company and seeking combat with the most dangerous representatives of Moghes wildlife. Should they meet another Guwandi, they are obliged to tell each other their stories, before drawing weapons and fighting to death: the winner is, however, responsible for taking care of the remains of their adversary.

Because of their dramatic exploits and honourable conduct, Guwandi are often seen as romantic heroes of Unathi society: misunderstood, punished, seeking penance in difficult trials. Sometimes they may return to their relatives after being pardoned; a few are granted a second outlook under the patronage of a different clan. In many cases, however, the reality of such life is much different from glossy legends that surround it. Plenty of exiles perish quickly on their own; those who survive are often pressured to steal and rob to make a living. In border regions with Guwandi presence the outcasts are often mistrusted or even attacked, forced to dwell in the darkness of the night.

Opinion on the practice had always been extremely divided, even within individual cultures; Yeosa, desert and savanna Sinta seem to favour it the most, although it is hardly universal. Clans of Diamond Peaks, with their well-developed legal codes and a system of corporal punishments in place, have always been ambivalent on the issue – while the path of Guwandi was deemed acceptable for some locals, the highlanders tend to ignore ancient rights of the exiles entering their realm, pushing Guwandi into service or making them settle down as farmers under the wing of a vassal clan. Allegedly, during the siege of Nolesk, some captured outcasts were unceremoniously forced to carry mortar rounds for Convent troops.

The rise of urban development and the emergence of Polar city-states led to a gradual decline in Guwandi population, since city growth has swallowed much of the surplus workforce. The practice itself is increasingly seen as dated or even barbaric. Nevertheless, Guwandi have become a staple character in the emerging mass literature of Moghes, often depicted in fictionalized or romanticized manner. Even so, real Guwandi can yet be encountered in the more remote locations of the planet.

=== The Precursors ===
Little is known about the Precursors – the race that settled Moghes approximately 100 thousand years ago. Unathi scholars have struggled for a long time to piece together a complete picture of them.

Some theorize that they were in fact ancient Unathi, given that some fairly advanced artifacts more or less fit the anatomy of modern-day Sinta and Yeosa. However, much of the complex equipment recovered since hints at the opposite, suggesting different physiology and biochemistry. An average Unathi, or even a humanoid cannot comfortably handle most artifacts of Precursor origin without awkward workarounds. Nevertheless, the idea persists among some clans.

A more common hypothesis holds that Precursors were a race of immense power, probably bipeds like Unathi, but with a more unique physiology. According to the supporters of this theory, the Unathi were not a part of this ancient race, but rather a product of it. Obtaining information from archeological digs of ancient bunkers found in the deserts and savannas, with the additional experience gleaned from human experiments in vat cloning, some researchers have come to the conclusion that Unathi were designed as a sort of biological weapon. Ostensibly, the Unathi were originally the protectors of the great race, created specifically to defend them against various dangers. While this school of thought is more consistent than the former, so far it is yet to produce solid evidence for Precursors' role in Unathi creation. Moreover, no existing pattern of Precursor armament is known to have accommodated Unathi anatomy in it's original form, suggesting that, if the bio-weapon theory was true, the Unathi were intended to be pushed into battle with no weapons to hold.

In recent years a different doctrine gained traction, elicited from some oral sources and the oldest recorded skeins. It claims that the Unathi of old have no relation to the Precursors, – in fact, the former have destroyed the latter. The assumption is based on the duality of uncovered artifacts, clearly divided between two different cultures possessing different anatomy and using different materials. Some researchers also point to similar notions in Moghes biosphere – while proper studies of Unathi genome have only just begun, biologists found it difficult to put together a comprehensive evolutionary tree of the planet's natural life, suggesting an influx of alien species at some point in Moghedi history. According to Gyska Ba’ask, a notable Unathi historian, the lands currently occupied by Unathi are actually the remnants of an ancient war that ravaged the planet and left it the way it is today. This theory has gained certain popularity in recent years, due in part to the increased knowledge of the history of the human race, and the interest in academic history in general. This concept is held true by all sorts of Unathi – all the way from polar progressives, rural conservatives to Diamond Peak nationalists. Nevertheless, this theory is far from being predominant, partially due to controversy surrounding it, especially among those that follow the Precursor faith.

There are dozens of other conjectures put forward by Unathi scholars, and more appear as the elements of the lost empire of Precursors are gradually unearthed. The ideas vary wildly, but not one has managed to get the grounding to gain universal acceptance. On its part, Humanity has undertaken research to figure out the exact origins of the Unathi as well, although conclusive results are yet to be produced.

== History and Politics ==
<blockquote>''Main Article: [[Timeline of Unathi History]]''</blockquote>Moghes was once inhabited by another species known as “The Precursors” who, according to the oral tradition, clashed with Unathi ancestor race an unknown number of years ago. Moghes was then a lush, garden world – however, the conflict took a toll on the planet's biosphere, reducing it to the contemporary meager state. Although the exact biology of the Precursors is unknown, it is assumed they weren't humanoid; a claim backed by some properties of the artifacts they left behind.

It is quite likely that the large amounts of radiation present during the extinction event led to mutations in Unathi ancestors, changing them in the process. Unathi are fascinated by the origins of their race, and some are almost obsessive in their desire to know all they can about Precursors and their relation to the Unathi race.

Although some accounts describe a poorly-documented encounter with humanoid aliens around '''2201''', relations with Humanity were formally “established” in '''2236''' by the leading clans of Mumbak. There was limited interest in the Unathi or their world right after the discovery, since it was largely overshadowed by the first contact with Skrell three years earlier.

In '''2239''', the '''Moghes Hegemony''' was created – a coalition crafted by the Kaahnepos of the dominant polar clans as a solid base for dealing with the outsiders. Despite being relatively close to Sol, Moghes was way off the established routes – in those very first years, private initiative far outstripped that of the government, even after a deal with the Hegemony was secured in '''2245;''' Since then, a considerable number of Unathi found work off-world, as mercenaries and in labor-intensive jobs.

In '''2260''', however, the [[Expeditionary Corps]] was allowed access to Precursor ruins on the planet, and to the incredible technology that these ruins held. These ruins were often the ones that the clans had already studied and gone through themselves, with new sites that are discovered either being overseen by the Hegemony, or Rah'Zakeh League. As time has gone on however, these restrictions have been slowly relaxed with the Expeditionary Corps now working with Unathi archaeologists to study new precursor ruins in recent times.

In '''2275''', the discovery of a particular Precursor ruin in the swamps led the Unathi to an archaic gate-like structure that, once Unathi engineers figured out how it worked, opened a portal or gateway of some kind to a separate ruin on a new world. As it would turn out, this new world was [[Ouere]], another planet in the Unathi System. Yet another artifact rush began, fueled by prospects of unexplored Precursor ruins. Intense friction began to rise through Unathi society, with the clans vying for control over new lands.

In '''2305''', some of the more welcoming (and powerful) Unathi Clans created an '''exchange program''' with SCG, allowing chosen clansmen to work as members of the Expeditionary Corps. In the meantime, members of the Expeditionary Corps are able to work and live amongst the Unathi. Positions in the program are allocated to the clans involved (often associated with the Hegemony), which sell, award or donate those to their allies, vassals or even enemies in return for benefits. Since opportunities like that are somewhat rare, exchange program seats often serve as bargaining chips in inter-clan relations.

=== The Hegemony ===
[[File:Unathi flag hegemony.png|thumb|The Hegemony Banner, sometimes used on formal occasions.]]
The '''Moghes Hegemony''' was created in 2239 by the ruling Kaahnepos of the major South Pole city-states, headed by Mumbak. Its formal purpose is to promote Unathi interests in trade and diplomacy with other species and create a better economy and network among Unathi living on Moghes. In practice, however, it is used to reinforce the role of the city-states in emerging off-world commerce and diplomacy, and to control the influx of foreign goods by the means of tariffs.

The Hegemony is headed by the so-called '''Council of Honourable Light'''; the seats are reserved for the Kaahnepos of major clans participating in city-state politics. New members are coopted; should a new city-state rise, Hegemony councilmen will try their best to have the Kaahnepos in charge submit to Hegemony regulations – using bribes, flattery and threats of violence. After that, the Kaahnepo in question may be awarded a seat or another position within Hegemony ranks. At this moment, the chief interests of the Council are:

* Pursuing a uniform tariff policy in trading with human empires like the [[Sol Central Government]] and the [[Gilgamesh Colonial Confederation]], as well as the [[Skrell]];
* Preventing the smuggling of Precursor and Ancestor-related artifacts off Moghes;
* Collecting data on alien industry/warfare/culture/commercial practices;
* Resolving possible conflicts between member clans;
* Investing in Guilds;
* Establishment of sovereign space and the creation of a mercantile fleet.

While Hegemony itself only includes a small share of clans, it has plenty of associates attached to it through the means of economic and cultural ties. Large savanna clans are a prime example; even though they might not be involved with the Hegemony directly, their wealth and influence in Polar affairs may affect Council decisions nevertheless.

=== The Convent ===
[[File:Unathi flag convent.png|thumb|The Grey Standard, used by Convent-aligned militias. Sometimes endearingly referred to as "The Rag".]]
While the Hegemony is often hailed as the first step towards making Moghes a powerhouse in the intergalactic community, those outside of Poles held less favourable views of the alliance. In '''2257''', '''Ssen-Uuma (Ssenuuma) Convent''' was established by a group of major highland Kaahnepos in a Diamond Peaks fortress of Ssen-Uuma, to act as a counterbalance to the growing Hegemony. Unlike their Polar counterparts, the Diamond Peak warbosses were more wary of developed alien races, considering those a possible threat to the established order, well-being and independence of Moghes. The rumours of Precursor artifacts being exchanged for energy weapons sparked an outrage among native population; in 2259, major riots occurred on the Southern Pole. In 2261, violence escalated further – the mercenary uprising in Nolesk, North Pole led to the capture of the city by Convent troops, which took over its first and only major spaceport.

While the Convent found support with plenty of highlander and desert clans, the city-states managed to secure the support of the majority of Savanna population, which drew its wealth from supplying the Poles with food. After a lengthy siege and several bloody skirmishes, the conflict began to subside – interestingly, it was one of the only two major conflicts recorded in Unathi history, the other one being the Cult War, which happened some 7,000 years before that.

Soon after the war ended, two organizations found themselves cooperating; Polar industry was in dire need of raw minerals provided by Diamond Peaks mines. In return, Ssen-Uuma member clans and their allies began to receive much-needed food, consumer goods and essential high-tech equipment. While both sides tend to hog the blanket with occasional embargo threats and saber rattling, both view status quo as an optimal outcome.

Like the Hegemony, Ssen-Uuma Convent is not a monolithic organization, but an alliance between most prominent clans of the area; the main difference between the two is that the latter has a military twist to it. The Convent is administered by the '''General Staff''', which is less inclusive yet more uniform than Hegemony Council; a strict ranking system is maintained, with the highest title of '''Srr-Kaahnepo''' awarded to the senior war-chiefs – a carry-over from the times where clan unions and vassalage system played the dominant role. Apart from preserving existing Unathi establishments (including traditional faith and the Grand Stratagem), the main concerns of the general staff are:

* Maintaining a regular military force in the Diamond Peaks for the benefit of the Convent;
* Supporting mercenaries operating off-Moghes;
* Gathering military and political intelligence regarding alien empires;
* Preparing for the possible invasion of the planet by an outside force.

Ultimately, the goals listed are interconnected, since they all serve the fourth, most important goal; by collecting data on outsider weapon systems, purchasing modern equipment and sending their youth to gain experience in alien warfare, Ssen-Uuma Convent hopes to gain the upper hand should the unthinkable happen – until then, keeping everything under wraps is a prudent thing to do.

=== Ouere ===
<blockquote>''Main Article: [[Ouere]]''</blockquote>The recently-discovered system of Precursor gateway devices connecting Moghes to its smaller sister planet of Ouere has seen many clans and small groups stepping through it into this new world. There is no clear consensus on how to treat this new world – either as a logical extension of Moghes, a completely new entity, or simply as a resource base for improving the home planet. Many colonists, artifact hunters and ostracised groups have flocked to the planet, with a [[Unathi Cults#Markesheli|Followers of Markesh]] community growing quite rapidly in numbers compared to other parts of Moghes.

This migration sparked the debate over Ouere-born Unathi. A large assembly, hosted in a desert dominion of Pakh with the support of Polar City-states ruled in favor of counting those born on Ouere as “native Unathi”, promoting the viewpoint that the land was naturally “blessed by Precursors”. While few reacted negatively to the ruling, it is hardly binding; the Diamond Peak clans have been claimed to avoid dealing directly with Ouere-based clans, either out or contempt, or unwilling to support the large Markesheli community there.

So far, only few permanent settlements exist on Ouere, with some under rapid construction, with renowned engineers and craftsmen coming to build up the new “utopia” for the Unathi. After a period of quick growth, in '''2302''' access to the world was limited by a Savanna clan of Guhr'sshki, which claimed many new territories early and took upon themselves to guard the new lands from undesirables – a move which